apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - {{ include "gateway.host" . }}
  gateways:
  - gsp-gsp-cluster.gsp-system
  http:
    - match:
      - uri:
          exact: /ServiceMetadata
      route:
        - destination:
            host: /etc/metadata/metadata.xml
            port:
              number: 80
    - route:
      - destination:
          host: {{ .Release.Name }}-gateway
          port:
            number: 80
