apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-gateway-redis-cluster-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gateway
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  podSelector:
    matchLabels:
      app: gateway-redis-cluster
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
    - from: # from gateway
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: gateway
            app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
      - protocol: TCP
        port: 6379
    - from: # from other gateway-redis-cluster pods
        - podSelector:
            matchLabels:
              app: gateway-redis-cluster
              release: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379