apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}-gateway-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Release.Name }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Release.Name }}-gateway-ingress-certificate
  dnsNames:
  - {{ include "gateway.host" . }}
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - {{ include "gateway.host" . }}
  issuerRef:
    name: letsencrypt-r53
    kind: ClusterIssuer
