apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}-metatron-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Release.Name }}-metatron
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Release.Name }}-metatron-ingress-certificate
  dnsNames:
  - {{ include "metatron.host" . }}
  issuerRef:
    name: letsencrypt-r53
    kind: ClusterIssuer
