{{ if .Values.stubConnector.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: metadata-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      deployment: {{ .Release.Name }}-proxy-node-metadata
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: connector
            app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
