apiVersion: verify.gov.uk/v1beta1
kind: CertificateRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ .Release.Name }}-proxy-node-metadata-signing-cert
  namespace: {{ .Release.Namespace }}
spec:
  countryCode: GB
  commonName: Verify Proxy Node Metadata Signing
  expiryMonths: 9
  organization: Cabinet Office
  organizationUnit: GDS
  location: London
  CACert: false
  certificateAuthority:
    secretName: proxy-node-metadata-ca
    namespace: {{ .Release.Namespace }}
