apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metadata-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metadata-service
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: {{ .Release.Name }}
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: mgmt
    port: 6001
    targetPort: mgmt
    protocol: TCP
  selector:
    app.kubernetes.io/name: metadata-service
    app.kubernetes.io/instance: {{ .Release.Name }}
