{{- if .Values.stubConnector.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-connector-metadata-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: connector-metadata
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  hosts:
  - {{ include "connector.metadata.host" . }}
  gateways:
  - gsp-gsp-cluster.gsp-system
  http:
    - route:
      - destination:
          host: {{ .Release.Name }}-connector-metadata
          port:
            number: 80
{{- end -}}
