{{- if .Values.stubConnector.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-stub-connector-gateway-egress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: proxy-node
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - {{ include "gateway.host" . }}
  gateways:
  - {{ .Release.Name }}-stub-connector-gateway-egress
  - mesh
  tls:
  - match:
    - gateways:
      - {{ .Release.Name }}-stub-connector-gateway-egress
      port: 443
      sniHosts:
      - {{ include "gateway.host" . }}
    route:
    - destination:
        host: {{ include "gateway.host" . }}
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - {{ include "gateway.host" . }}
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: {{ .Release.Name }}-stub-connector-gateway-egress
        port:
          number: 443
      weight: 100
{{- end }}
