{{- if .Values.stubConnector.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-connector-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-connector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  secretName: {{ .Release.Name }}-connector-ingress-certificate
  dnsNames:
  - {{ include "stubConnector.host" . }}
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - {{ include "stubConnector.host" . }}
  issuerRef:
    name: letsencrypt-r53
    kind: ClusterIssuer
{{- end -}}
