{{- if .Values.stubConnector.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-connector
  labels:
    app.kubernetes.io/name: connector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  hosts:
  - {{ include "connector.host" . }}
  gateways:
  - gsp-gsp-cluster.gsp-system
  http:
    - match:
      - uri:
          exact: /ConnectorMetadata
      route:
        - destination:
            host: /etc/metadata/metadata.xml
            port:
              number: 80
    - route:
      - destination:
          host: {{ .Release.Name }}-connector
          port:
            number: 80
{{- end -}}
