---
apiVersion: verify.gov.uk/v1beta1
kind: CertificateRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: proxy-node-metadata-ca
  namespace: sandbox-proxy-node-dev
spec:
  countryCode: GB
  commonName: Verify Sandbox Dev Metadata CA
  expiryMonths: 120
  organization: Cabinet Office
  organizationUnit: GDS
  location: London
  CACert: true
  certificateAuthority:
    secretName: verify-root-ca-test
    namespace: sandbox-metadata-controller
